package com.arcane.mod; 

import java.util.Arrays;

import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.EnumEnchantmentType;
import net.minecraftforge.common.MinecraftForge;

import com.arcane.mod.common.CommonProxy;
import com.arcane.mod.enchantments.EnchantmentArmorRegen;
import com.arcane.mod.enchantments.EnchantmentArrowExplosive;
import com.arcane.mod.enchantments.EnchantmentArrowLightning;
import com.arcane.mod.enchantments.EnchantmentArrowSeeking;
import com.arcane.mod.enchantments.EnchantmentCritical;
import com.arcane.mod.enchantments.EnchantmentFlameTouch;
import com.arcane.mod.enchantments.EnchantmentJumpBoost;
import com.arcane.mod.enchantments.EnchantmentLeadFooted;
import com.arcane.mod.enchantments.EnchantmentPoison;
import com.arcane.mod.enchantments.EnchantmentSpeedBoost;
import com.arcane.mod.enchantments.EnchantmentSprinter;
import com.arcane.mod.hooks.ArmorEventHookContainer;
import com.arcane.mod.hooks.ArrowEventHookContainer;
import com.arcane.mod.hooks.ToolEventHookContainer;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = "MrArcane_ArcaneEnchantments", name = "Arcane Enchantments", version = "1.0.7")
@NetworkMod(clientSideRequired = true, serverSideRequired = true)

public class ArcaneEnchantments
{ 
	// TODO: I need to completely rework the min/max enchant system...I done goofed
	// The first integer in the statement is the Enchantment ID, and the second is the rarity
	public static final Enchantment flameTouch = new EnchantmentFlameTouch(103, 2);
	
	// Arrow Enchantments
	public static final Enchantment arrowSeeking = new EnchantmentArrowSeeking(74, 1);
	public static final Enchantment arrowExplosive = new EnchantmentArrowExplosive(72, 4);
	public static final Enchantment arrowPoison = new EnchantmentPoison(94, 2, EnumEnchantmentType.bow);
	public static final Enchantment swordPoison = new EnchantmentPoison(85, 2, EnumEnchantmentType.weapon);
	public static final Enchantment arrowCritical = new EnchantmentCritical(98, 6, EnumEnchantmentType.bow);
	public static final Enchantment swordCritical = new EnchantmentCritical(99, 6, EnumEnchantmentType.weapon);
	public static final Enchantment arrowLightning = new EnchantmentArrowLightning(73, 2);
	
	// Armor Enchantments
	public static final Enchantment jumpBoost = new EnchantmentJumpBoost(104, 3);
	public static final Enchantment leadFooted = new EnchantmentLeadFooted(95, 5);
	public static final Enchantment armorRegen = new EnchantmentArmorRegen(102, 1);
	public static final Enchantment sprinter = new EnchantmentSprinter(92, 4);
	public static final Enchantment speedBoost = new EnchantmentSpeedBoost(84, 5);
	
	/*
	public static final Enchantment allBound;
	public static final Enchantment arrowHoly;
	public static final Enchantment arrowCripple;
	public static final Enchantment hoeHarvester;
	public static final Enchantment swordCleverness;
	public static final Enchantment bootsSpeed;
	public static final Enchantment swordPoison;
	public static final Enchantment swordGuard;
	public static final Enchantment arrowLooting;
	public static final Enchantment armorReflection;
	public static final Enchantment arrowCleverness;
	public static final Enchantment arrowSpeed;
	public static final Enchantment axeLumberjack;
	public static final Enchantment armorDeflection;
	public static final Enchantment arrowPoison;
	public static final Enchantment swordRage;
	public static final Enchantment arrowRage;
	public static final Enchantment platePoisonResistance;
	*/

	@SidedProxy(serverSide = "com.arcane.mod.common.CommonProxy", clientSide = "com.arcane.mod.client.ClientProxy")
	public static CommonProxy proxy;
	@Mod.Instance("Arcane_Enchantments")
	public static ArcaneEnchantments instance;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{        
		getModMeta(event.getModMetadata());     
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
        MinecraftForge.EVENT_BUS.register(new ArrowEventHookContainer());
        MinecraftForge.EVENT_BUS.register(new ArmorEventHookContainer());
        MinecraftForge.EVENT_BUS.register(new ToolEventHookContainer());
        proxy.load();
	}
	

	private void getModMeta(ModMetadata meta)
	{
		meta.authorList = Arrays.asList(new String[] {"MrArcane111"});
		meta.logoFile = "";
		meta.autogenerated = false;
		meta.credits = "";
		meta.description = "Adds __ new enchantments. Happy enchanting!";
		meta.url = "";
	}
	
	public static String getVersion()
    {
        return "1.6.4";
    }

    public static String getModName()
    {
        return "ArcaneEnchantments";
    }
}